/**
 * File storage.
 *
 * Local disk today, behind an interface shaped like object storage so moving
 * to S3 later is a change to this file alone. Nothing outside it knows where
 * bytes actually live - callers only ever hold an opaque storage key.
 */

import 'server-only'
import { createHash, randomUUID } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, extname, join, resolve, sep } from 'node:path'

/** Extensions we will accept, whatever a template's slot asks for (spec §39). */
const ALLOWED_EXTENSIONS = new Set([
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'csv',
  'ppt',
  'pptx',
  'txt',
  'png',
  'jpg',
  'jpeg',
  'webp',
  'gif',
])

export const MAX_FILE_BYTES = 25 * 1024 * 1024

/**
 * Statically scoped to one folder under the project root.
 *
 * Building the root from a literal rather than an environment variable keeps
 * the bundler's file tracing narrow; otherwise the whole project is traced
 * into the deployment output.
 */
const UPLOAD_DIR_NAME = 'uploads'

function uploadRoot(): string {
  return join(process.cwd(), UPLOAD_DIR_NAME)
}

export function extensionOf(fileName: string): string {
  return extname(fileName).replace('.', '').toLowerCase()
}

export interface StoredFile {
  storageKey: string
  sizeBytes: number
  checksum: string
}

export class FileRejected extends Error {}

/**
 * Write an upload and return its locator.
 *
 * The stored name is generated rather than taken from the upload, so a
 * hostile filename can never influence the path written to.
 */
export async function storeFile(params: {
  instanceId: string
  file: File
  allowedExtensions?: string[]
}): Promise<StoredFile> {
  const { instanceId, file } = params

  if (file.size === 0) throw new FileRejected('That file is empty.')
  if (file.size > MAX_FILE_BYTES) {
    throw new FileRejected(
      `Files must be ${Math.floor(MAX_FILE_BYTES / 1024 / 1024)}MB or smaller.`,
    )
  }

  const extension = extensionOf(file.name)
  if (!ALLOWED_EXTENSIONS.has(extension)) {
    throw new FileRejected(`${extension || 'That file type'} is not an accepted file type.`)
  }

  const allowed = params.allowedExtensions
  if (allowed && allowed.length > 0 && !allowed.includes(extension)) {
    throw new FileRejected(`This step accepts ${allowed.join(', ')} files.`)
  }

  const bytes = Buffer.from(await file.arrayBuffer())
  // Built as a plain relative key rather than with `join`, so it stays a
  // portable locator: the same string will address an object store later.
  const storageKey = `${sanitiseSegment(instanceId)}/${randomUUID()}.${extension}`
  const destination = join(uploadRoot(), storageKey)

  await mkdir(dirname(destination), { recursive: true })
  await writeFile(destination, bytes)

  return {
    storageKey,
    sizeBytes: bytes.byteLength,
    checksum: createHash('sha256').update(bytes).digest('hex'),
  }
}

/** Read a stored file back. Rejects any key that tries to escape the root. */
export async function readStoredFile(storageKey: string): Promise<Buffer> {
  const root = uploadRoot()
  const target = resolve(root, storageKey)

  // A key is generated by this module, but it round-trips through the
  // database, so it is treated as untrusted on the way back in.
  if (target !== root && !target.startsWith(root + sep)) {
    throw new FileRejected('Invalid file location.')
  }
  return readFile(target)
}

function sanitiseSegment(value: string): string {
  return value.replace(/[^A-Za-z0-9._-]/g, '_')
}
