/**
 * Podcast Production — the second workflow (spec §53).
 *
 * This exists to prove the point the brief makes in §34 and §52: the product
 * is the engine, not the proposal process. Nothing in the engine or the
 * interface changed to support this file. It is a different department, a
 * different shape and a different length, expressed entirely as data.
 */

import type { WorkflowTemplateSeed } from './types'

export const PODCAST_PRODUCTION_WORKFLOW: WorkflowTemplateSeed = {
  key: 'podcast_production',
  name: 'Podcast Production',
  description: 'From an episode idea through to a published episode and clips.',
  projectKey: 'podcast',
  departmentKey: 'content',
  initialStageKey: 'podcast_request',
  stages: [
    {
      key: 'podcast_request',
      name: 'Podcast Request',
      description: 'Record the episode idea and the guest being approached.',
      instructions:
        'Capture the episode topic, who the guest is, and when it needs to go out.',
      assignees: [{ mode: 'role', roleKey: 'podcast_producer' }],
      completionRule: 'any',
      fields: [
        { key: 'episode_title', label: 'Episode title', type: 'text', required: true },
        { key: 'episode_topic', label: 'Topic', type: 'textarea', required: true },
        { key: 'guest_name', label: 'Guest name', type: 'text', required: true },
        { key: 'guest_email', label: 'Guest email', type: 'email', required: true },
        { key: 'target_publish_date', label: 'Target publish date', type: 'date', required: true },
      ],
      files: [],
      checklist: [],
      priority: 'medium',
      dueInHours: 24,
      slaHours: 24,
      requiresApproval: false,
      nextStageKey: 'guest_confirmation',
    },
    {
      key: 'guest_confirmation',
      name: 'Guest Confirmation',
      description: 'The host agrees a date with the guest.',
      instructions: 'Contact the guest, agree a recording slot, and record it here.',
      assignees: [{ mode: 'role', roleKey: 'podcast_host' }],
      completionRule: 'any',
      fields: [
        { key: 'recording_slot', label: 'Agreed recording date', type: 'date', required: true },
        {
          key: 'recording_format',
          label: 'Format',
          type: 'select',
          required: true,
          options: ['In studio', 'Remote', 'Hybrid'],
        },
      ],
      files: [],
      checklist: [],
      priority: 'high',
      dueInHours: 48,
      slaHours: 48,
      requiresApproval: false,
      nextStageKey: 'research',
    },
    {
      key: 'research',
      name: 'Research',
      description: 'Background on the guest and the topic.',
      instructions:
        'Research the guest and the subject, and attach a brief the host can read before recording.',
      assignees: [{ mode: 'role', roleKey: 'content_writer' }],
      completionRule: 'any',
      fields: [
        { key: 'research_summary', label: 'Research summary', type: 'textarea', required: true },
      ],
      files: [
        { key: 'research_brief', label: 'Research brief', required: false, acceptedExtensions: ['pdf', 'doc', 'docx'] },
      ],
      checklist: [],
      priority: 'medium',
      dueInHours: 48,
      slaHours: 48,
      requiresApproval: false,
      nextStageKey: 'questions',
    },
    {
      key: 'questions',
      name: 'Questions',
      description: 'The interview outline.',
      instructions: 'Draft the questions from the research, in the order you want to ask them.',
      assignees: [{ mode: 'role', roleKey: 'content_writer' }],
      completionRule: 'any',
      fields: [
        { key: 'question_list', label: 'Questions', type: 'textarea', required: true },
      ],
      files: [],
      checklist: [],
      priority: 'medium',
      dueInHours: 24,
      slaHours: 24,
      requiresApproval: false,
      nextStageKey: 'recording',
    },
    {
      key: 'recording',
      name: 'Recording',
      description: 'The session itself.',
      instructions: 'Record the episode, then note how it went.',
      // Host and producer are both in the room. Either can close the stage,
      // the same shared-stage rule the proposal process uses for deliverables.
      assignees: [
        { mode: 'role', roleKey: 'podcast_host' },
        { mode: 'role', roleKey: 'podcast_producer' },
      ],
      completionRule: 'any',
      fields: [
        { key: 'recorded_on', label: 'Recorded on', type: 'date', required: true },
        { key: 'duration_minutes', label: 'Duration (minutes)', type: 'number', required: true },
        { key: 'recording_notes', label: 'Notes', type: 'textarea', required: false },
      ],
      files: [],
      checklist: [],
      priority: 'high',
      dueInHours: 24,
      slaHours: 24,
      requiresApproval: false,
      nextStageKey: 'raw_footage_upload',
    },
    {
      key: 'raw_footage_upload',
      name: 'Raw Footage Upload',
      description: 'Hand the recording to the editor.',
      instructions: 'Upload the raw recording so editing can begin.',
      assignees: [{ mode: 'role', roleKey: 'podcast_producer' }],
      completionRule: 'any',
      fields: [],
      files: [{ key: 'raw_footage', label: 'Raw recording', required: true }],
      checklist: [],
      priority: 'high',
      dueInHours: 12,
      slaHours: 12,
      requiresApproval: false,
      nextStageKey: 'editing',
    },
    {
      key: 'editing',
      name: 'Editing',
      description: 'Cut the episode.',
      instructions:
        'Edit the recording into the final episode: trim, balance the audio, and add the intro and outro.',
      assignees: [{ mode: 'role', roleKey: 'video_editor' }],
      completionRule: 'any',
      fields: [],
      files: [{ key: 'edited_episode', label: 'Edited episode', required: true }],
      checklist: [],
      priority: 'high',
      dueInHours: 72,
      slaHours: 72,
      requiresApproval: false,
      nextStageKey: 'quality_check',
    },
    {
      key: 'quality_check',
      name: 'Quality Check',
      description: 'Review before it goes to approval.',
      instructions: 'Check the edit against every item below before sending it for approval.',
      assignees: [{ mode: 'role', roleKey: 'podcast_producer' }],
      completionRule: 'any',
      fields: [],
      files: [],
      checklist: [
        { key: 'audio_levels', label: 'Audio levels balanced', group: 'Audio', required: true },
        { key: 'no_dead_air', label: 'No dead air or long pauses', group: 'Audio', required: true },
        { key: 'intro_outro', label: 'Intro and outro in place', group: 'Structure', required: true },
        { key: 'names_correct', label: 'Guest name and title correct', group: 'Structure', required: true },
        { key: 'runtime', label: 'Runtime within target', group: 'Structure', required: true },
      ],
      priority: 'high',
      dueInHours: 24,
      slaHours: 24,
      requiresApproval: false,
      nextStageKey: 'approval',
    },
    {
      key: 'approval',
      name: 'Approval',
      description: 'Sign the episode off for publishing.',
      instructions: 'Listen through and approve, or send it back with what needs changing.',
      assignees: [{ mode: 'role', roleKey: 'management' }],
      completionRule: 'any',
      fields: [],
      files: [],
      checklist: [],
      priority: 'urgent',
      dueInHours: 24,
      slaHours: 24,
      requiresApproval: true,
      // Rejected episodes go back to the edit, not to the quality check.
      rejectTargetStageKey: 'editing',
      nextStageKey: 'clips',
    },
    {
      key: 'clips',
      name: 'Clips',
      description: 'Short cuts for social.',
      instructions: 'Cut the approved episode into short clips and upload them.',
      assignees: [{ mode: 'role', roleKey: 'video_editor' }],
      completionRule: 'any',
      fields: [
        { key: 'clip_count', label: 'Number of clips', type: 'number', required: true },
      ],
      files: [{ key: 'social_clips', label: 'Social clips', required: true }],
      checklist: [],
      priority: 'medium',
      dueInHours: 48,
      slaHours: 48,
      requiresApproval: false,
      nextStageKey: 'publishing',
    },
    {
      key: 'publishing',
      name: 'Publishing',
      description: 'Put the episode out.',
      instructions: 'Publish the episode and record where it went live.',
      assignees: [{ mode: 'role', roleKey: 'podcast_producer' }],
      completionRule: 'any',
      fields: [
        { key: 'published_url', label: 'Published URL', type: 'text', required: true },
        { key: 'published_on', label: 'Published on', type: 'date', required: true },
      ],
      files: [],
      checklist: [],
      priority: 'high',
      dueInHours: 24,
      slaHours: 24,
      requiresApproval: false,
      nextStageKey: null,
    },
  ],
}
